namespace Iprofile.Config
{
    public static class Settings
    {

        private static string settings = @"{
            'iprofile::authTitle':{
                'description':'Titulo',
                'view':'settingField',
                'translatable':true,
                'name':'iprofile::authTitle',
                'isTranslatable':true,
                'translations':[{'locale':'es'}]
            },
            'iprofile::authLoginCaption':{
                'description':'Subtitulo para Inicio de Sesión',
                'view':'settingField',
                'translatable':true,
                'name':'iprofile::authLoginCaption',
                'isTranslatable':true,
                'translations':[{'locale':'es'}]
            },
            'iprofile::authRegisterCaption':{
                'description':'Subtitulo para Registro',
                'view':'settingField',
                'translatable':true,
                'name':'iprofile::authRegisterCaption',
                'isTranslatable':true,
                'translations':[{'locale':'es'}]
            },
            'iprofile::registerUsers':{
                'description':'',
                'default':'0',
                'view':'settingField',
                'translatable':false,
                'id':21,
                'name':'iprofile::registerUsers',
                'plainValue':'0',
                'isTranslatable':false,
                'created_at':'2022-03-01T22:54:03.000000Z',
                'updated_at':'2022-03-01T22:54:03.000000Z',
                'value':'0',
                'translations':[]
            },
            'iprofile::validateRegisterWithEmail':{
                'description':'',
                'default':'0',
                'view':'settingField',
                'translatable':false,
                'id':22,
                'name':'iprofile::validateRegisterWithEmail',
                'plainValue':'0',
                'isTranslatable':false,
                'created_at':'2022-03-01T22:54:03.000000Z',
                'updated_at':'2022-03-01T22:54:03.000000Z',
                'value':'0',
                'translations':[]
            },
            'iprofile::adminNeedsToActivateNewUsers':{
                'description':'',
                'default':'0',
                'view':'settingField',
                'translatable':false,
                'id':23,
                'name':'iprofile::adminNeedsToActivateNewUsers',
                'plainValue':'0',
                'isTranslatable':false,
                'created_at':'2022-03-01T22:54:03.000000Z',
                'updated_at':'2022-03-01T22:54:03.000000Z',
                'value':'0',
                'translations':[]
            },
            'iprofile::registerUsersWithSocialNetworks':{
                'description':'',
                'default':'0',
                'view':'settingField',
                'translatable':false,
                'id':24,
                'name':'iprofile::registerUsersWithSocialNetworks',
                'plainValue':'0',
                'isTranslatable':false,
                'created_at':'2022-03-01T22:54:03.000000Z',
                'updated_at':'2022-03-01T22:54:03.000000Z',
                'value':'0',
                'translations':[]
            },
            'iprofile::registerUserWithPoliticsOfPrivacy':{
                'description':'',
                'view':'settingField',
                'translatable':false,
                'id':25,
                'name':'iprofile::registerUserWithPoliticsOfPrivacy',
                'isTranslatable':false,
                'created_at':'2022-03-01T22:54:03.000000Z',
                'updated_at':'2022-03-01T22:54:03.000000Z',
                'translations':[]
            },
            'iprofile::registerUserWithTermsAndConditions':{
                'description':'',
                'view':'settingField',
                'translatable':false,
                'id':26,
                'name':'iprofile::registerUserWithTermsAndConditions',
                'isTranslatable':false,
                'created_at':'2022-03-01T22:54:03.000000Z',
                'updated_at':'2022-03-01T22:54:03.000000Z',
                'translations':[]
             },
            'iprofile::rolesToDirectory':{
                'description':'',
                'default':'[2]',
                'view':'settingField',
                'translatable':false,
                'id':27,
                'name':'iprofile::rolesToDirectory',
                'plainValue':['2'],
                'isTranslatable':false,
                'created_at':'2022-03-01T22:54:03.000000Z',
                'updated_at':'2022-03-01T22:54:03.000000Z',
                'value':['2'],
                'translations':[]
            },
            'iprofile::authBanner':{
                'description':'Banner',
                'default':'',
                'view':'settingField',
                'translatable':false,
                'name':'iprofile::authBanner',
                'isTranslatable':false,
                'plainValue':{'medias_single':{}},
                'value':{'medias_single':{}},
                'media':{'mimeType':'image/jpeg','path':'https://agidev.blob.core.windows.net/agione/Background-AGI.jpg'}
            },
            'iprofile::hideLogo':{
                'description':'Ocultar Logo',
                'default':'0',
                'view':'settingField',
                'translatable':false,
                'name':'iprofile::hideLogo',
                'isTranslatable':false,
                'plainValue':'0',
                'value':'0'
            },
            'iprofile::rolesToRegister':{
                'description':'Roles habilitados para registro',
                'default':'[2]',
                'view':'settingField',
                'translatable':false,
                'name':'iprofile::rolesToRegister',
                'isTranslatable':false,
                'plainValue':[2],
                'value':[2]
            },
            'iprofile::tenantWithCentralData':{
                'description':'Entidades con data central',
                'default':'[]',
                'view':'settingField',
                'translatable':false,
                'name':'iprofile::tenantWithCentralData',
                'isTranslatable':false,
                'plainValue':[],
                'value':[]
            },
            'iprofile::allowLocalLogin':{
                'default':'1',
                'description':'Permitir login local',
                'isTranslatable':false,
                'name':'iprofile::allowLocalLogin',
                'onlySuperAdmin':true,
                'plainValue':'0',
                'translatable':false,
                'value':'0',
                'view':'settingField'
            },
            'iprofile::registerUsersWithSocialNetworks':{
                'default':'0',
                'description':'Permitir registro con redes sociales',
                'isTranslatable':false,
                'name':'iprofile::registerUsersWithSocialNetworks',
                'onlySuperAdmin':true,
                'plainValue':'1',
                'translatable':false,
                'value':'1',
                'view':'settingField'
            }
        }";

        public static string GetSettings()
        {
            return settings;
        }
    }
}
